package com.xiaoyuanzhu.hiagent.android.core

import android.content.Context
import android.os.Build
import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import android.util.Base64
import java.security.KeyStore
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec

class CredentialException(message: String, cause: Throwable? = null) :
    Exception(message, cause)

/**
 * Where the long-lived credential lives — the iOS Keychain's opposite number.
 *
 * The key is generated inside the Android Keystore and is not extractable, so
 * what lands in `SharedPreferences` is ciphertext that only this app on this
 * handset can open. `setUnlockedDeviceRequired(true)` is the direct analog of
 * the iOS store's `kSecAttrAccessibleAfterFirstUnlockThisDeviceOnly`: readable
 * while the person is using the device, never off a powered-down one, and never
 * on another device.
 *
 * Keystore-direct rather than `androidx.security:security-crypto` — that library
 * wraps exactly this and adds a dependency whose maintenance we would then be
 * downstream of, for about forty lines of code.
 *
 * As on iOS, the credential never reaches the WebView, JavaScript, or any file
 * the OS backs up. See `data_extraction_rules.xml`.
 */
class CredentialStore(context: Context) {
    private val prefs = context.applicationContext
        .getSharedPreferences("hi.agent.credentials", Context.MODE_PRIVATE)

    fun save(value: String, account: String) {
        try {
            val cipher = Cipher.getInstance(TRANSFORMATION)
            cipher.init(Cipher.ENCRYPT_MODE, secretKey())
            val sealed = cipher.doFinal(value.toByteArray(Charsets.UTF_8))
            // The IV is generated by the cipher and is not a secret; it just has
            // to travel with the ciphertext it belongs to.
            val packed = cipher.iv + sealed
            prefs.edit()
                .putString(account, Base64.encodeToString(packed, Base64.NO_WRAP))
                .apply()
        } catch (e: Exception) {
            throw CredentialException("Could not save the core credential.", e)
        }
    }

    fun read(account: String): String {
        val stored = prefs.getString(account, null)
            ?: throw CredentialException("No credential is stored for this core.")
        return try {
            val packed = Base64.decode(stored, Base64.NO_WRAP)
            val cipher = Cipher.getInstance(TRANSFORMATION)
            cipher.init(
                Cipher.DECRYPT_MODE,
                secretKey(),
                GCMParameterSpec(TAG_BITS, packed, 0, IV_BYTES),
            )
            val plain = cipher.doFinal(packed, IV_BYTES, packed.size - IV_BYTES)
            String(plain, Charsets.UTF_8)
        } catch (e: Exception) {
            // A wiped Keystore key — which a lock-screen change or a restore onto
            // another handset can cause — lands here. To the reader that is the
            // same fact as "no credential": this device is not paired any more.
            throw CredentialException("The stored credential could not be read.", e)
        }
    }

    fun delete(account: String) {
        prefs.edit().remove(account).apply()
    }

    private fun secretKey(): SecretKey {
        val keyStore = KeyStore.getInstance(PROVIDER).apply { load(null) }
        (keyStore.getEntry(KEY_ALIAS, null) as? KeyStore.SecretKeyEntry)?.let {
            return it.secretKey
        }

        val generator = KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, PROVIDER)
        val spec = KeyGenParameterSpec.Builder(
            KEY_ALIAS,
            KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT,
        )
            .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
            .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
            .setKeySize(256)
            // No user-authentication requirement: the shell re-exchanges the
            // credential when the app is foregrounded and on network
            // restoration, and a key that needs a fresh unlock would turn those
            // into prompts the person did not ask for.
            .setUserAuthenticationRequired(false)
            .apply {
                if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) {
                    setUnlockedDeviceRequired(true)
                }
            }
            .build()
        generator.init(spec)
        return generator.generateKey()
    }

    companion object {
        private const val PROVIDER = "AndroidKeyStore"
        private const val KEY_ALIAS = "hi.agent.credential.v1"
        private const val TRANSFORMATION = "AES/GCM/NoPadding"
        private const val IV_BYTES = 12
        private const val TAG_BITS = 128

        fun account(id: String) = "credential.$id"
    }
}
