#!/usr/bin/env bash
#
# Describe a release's artifacts as one JSON file, so that "what is the current
# version and where do I download it" has a machine answer.
#
# The output is attached to the GitHub Release under the *unversioned* name
# `manifest.json`, which is the whole point: GitHub resolves
#
#   https://github.com/<owner>/<repo>/releases/latest/download/manifest.json
#
# only for a filename that does not change between releases. That URL is the
# seam a download page reads instead of hardcoding an artifact name — today
# hi-agent.xyz hardcodes `/downloads/hi-agent-macos-latest.dmg`, which is a
# second place the version has to be remembered.
#
# The expected filenames are *derived from VERSION, not discovered from the
# directory*, and a missing or empty one is a hard error. That is deliberate:
# `make dmg` on a Mac whose disk filled mid-build reports success and produces
# nothing, and a manifest generated by globbing would quietly ship four
# artifacts where five were promised. Naming what must be there is the only
# check that catches it.
#
#   DIST=DIR       directory holding the built artifacts (default: target/dist)
#   TAG=v0.2.0     release tag       (default: v<VERSION>)
#   REPO=owner/n   GitHub repository (default: $GITHUB_REPOSITORY, else the
#                  origin remote)
#   COMMIT=SHA     commit the release is cut from (default: git HEAD)
#   RELEASED=TS    RFC 3339 UTC timestamp (default: now)
#   MACOS_NOTARIZED=1  the .dmg passed `xcrun stapler validate` on the builder
#   ONLY=a,b       restrict to a subset of artifact keys, for partial runs
#                  (keys: macos, linux, windows, android, android-tv)
#   OUT=PATH       where to write the JSON (default: $DIST/manifest.json)
#
# Output: the manifest path on stdout, the JSON itself at $OUT.
set -euo pipefail

cd "$(dirname "$0")/.."
ROOT="$(pwd)"

VERSION="$(tr -d '\r\n' < VERSION)"
DIST="${DIST:-$ROOT/target/dist}"
TAG="${TAG:-v$VERSION}"
OUT="${OUT:-$DIST/manifest.json}"

[ -d "$DIST" ] || { echo "error: DIST directory not found: $DIST" >&2; exit 1; }

# `owner/repo`. In Actions this is handed to us; locally, dig it out of the
# remote so the URLs a local run produces are the real ones and can be checked.
REPO="${REPO:-${GITHUB_REPOSITORY:-}}"
if [ -z "$REPO" ]; then
  origin="$(git -C "$ROOT" remote get-url origin 2>/dev/null || true)"
  origin="${origin%.git}"
  case "$origin" in
    *github.com[:/]*) REPO="${origin#*github.com}"; REPO="${REPO#[:/]}" ;;
  esac
fi
[ -n "$REPO" ] || { echo "error: REPO is unset and no github origin remote found" >&2; exit 1; }

COMMIT="${COMMIT:-${GITHUB_SHA:-$(git -C "$ROOT" rev-parse HEAD 2>/dev/null || echo '')}}"
RELEASED="${RELEASED:-$(date -u +%Y-%m-%dT%H:%M:%SZ)}"

# --- the artifact table -----------------------------------------------------
# One row per downloadable thing, tab-separated:
#
#   key  filename  platform  arch  kind  device  signed
#
# `signed` is a statement of record, not a guess. Only macOS is signed today,
# and only when the builder had a Developer ID — see the fixup below. The .deb,
# the NSIS installer and both APKs are unsigned: `docs/platforms/android.md`
# records that no signing config is committed, and `docs/platforms/windows.md`
# names Authenticode as an external gate nobody has passed. When any of those
# gains a signature, this column is where it is said.
#
# iOS is deliberately absent. It ships through TestFlight
# (.github/workflows/ios-testflight.yml) and an .ipa is not a thing anyone can
# download and install, so listing one would describe a download that isn't.
ARTIFACTS=$(cat <<TABLE
macos	hi-agent-$VERSION-macos-apple-silicon.dmg	macos	arm64	dmg	desktop	true
linux	hi-agent_${VERSION}_amd64.deb	linux	amd64	deb	desktop	false
windows	hi-agent-$VERSION-windows-x64.exe	windows	x64	nsis	desktop	false
android	hi-agent-$VERSION-android.apk	android	universal	apk	handset	false
android-tv	hi-agent-$VERSION-android-tv.apk	android	universal	apk	tv	false
TABLE
)

# ONLY= restricts the table, for a run that deliberately builds a subset. It is
# not a way to tolerate a failed build: a key left in the table must be present.
if [ -n "${ONLY:-}" ]; then
  wanted=",${ONLY//[[:space:]]/},"
  filtered=""
  while IFS=$'\t' read -r key rest; do
    [ -n "$key" ] || continue
    case "$wanted" in *",$key,"*) filtered+="$key	$rest"$'\n' ;; esac
  done <<< "$ARTIFACTS"
  [ -n "$filtered" ] || { echo "error: ONLY='$ONLY' selected no known artifacts" >&2; exit 1; }
  ARTIFACTS="${filtered%$'\n'}"
fi

sha256_of() {
  if command -v sha256sum >/dev/null 2>&1; then sha256sum "$1" | awk '{print $1}'
  else shasum -a 256 "$1" | awk '{print $1}'; fi
}

size_of() {
  # BSD stat and GNU stat disagree on the flag; ask both.
  stat -c%s "$1" 2>/dev/null || stat -f%z "$1"
}

# --- collect, checking as we go --------------------------------------------
missing=()
rows=()
while IFS=$'\t' read -r key file platform arch kind device signed; do
  [ -n "$key" ] || continue
  path="$DIST/$file"
  if [ ! -f "$path" ]; then
    missing+=("$file (no such file)")
    continue
  fi
  if [ ! -s "$path" ]; then
    missing+=("$file (zero bytes)")
    continue
  fi

  # A macOS build with no Developer ID falls back to ad-hoc signing, which is
  # not a signature anyone downloading this can act on. The builder tells us
  # which happened; absent that we say false, because claiming a signature we
  # did not verify is worse than understating one we have.
  notarized=false
  if [ "$key" = "macos" ]; then
    if [ "${MACOS_NOTARIZED:-}" = "1" ]; then notarized=true; else signed=false; fi
  fi

  rows+=("$key"$'\t'"$file"$'\t'"$platform"$'\t'"$arch"$'\t'"$kind"$'\t'"$device"$'\t'"$signed"$'\t'"$notarized"$'\t'"$(size_of "$path")"$'\t'"$(sha256_of "$path")")
done <<< "$ARTIFACTS"

if (( ${#missing[@]} > 0 )); then
  echo "error: $DIST is missing artifacts this release promises:" >&2
  printf '  - %s\n' "${missing[@]}" >&2
  echo "       (a zero-byte file usually means the build host ran out of disk" >&2
  echo "        and the packaging step reported success anyway)" >&2
  exit 1
fi

# --- emit -------------------------------------------------------------------
base="https://github.com/$REPO/releases/download/$TAG"

mkdir -p "$(dirname "$OUT")"
{
  printf '{\n'
  printf '  "schema": 1,\n'
  printf '  "version": "%s",\n' "$VERSION"
  printf '  "tag": "%s",\n' "$TAG"
  printf '  "commit": "%s",\n' "$COMMIT"
  printf '  "released": "%s",\n' "$RELEASED"
  printf '  "release": "https://github.com/%s/releases/tag/%s",\n' "$REPO" "$TAG"
  printf '  "artifacts": [\n'
  first=true
  for row in "${rows[@]}"; do
    IFS=$'\t' read -r key file platform arch kind device signed notarized size sha <<< "$row"
    $first || printf ',\n'
    first=false
    printf '    {\n'
    printf '      "id": "%s",\n' "$key"
    printf '      "platform": "%s",\n' "$platform"
    printf '      "arch": "%s",\n' "$arch"
    printf '      "kind": "%s",\n' "$kind"
    printf '      "device": "%s",\n' "$device"
    printf '      "file": "%s",\n' "$file"
    printf '      "url": "%s/%s",\n' "$base" "$file"
    printf '      "size": %s,\n' "$size"
    printf '      "sha256": "%s",\n' "$sha"
    printf '      "signed": %s,\n' "$signed"
    printf '      "notarized": %s\n' "$notarized"
    printf '    }'
  done
  printf '\n  ]\n'
  printf '}\n'
} > "$OUT"

# Parse what we just wrote rather than trusting the printf above. A manifest
# that is not valid JSON fails here, on the machine that made it, instead of in
# whatever reads it a week later.
if command -v python3 >/dev/null 2>&1; then
  python3 -c 'import json,sys; json.load(open(sys.argv[1]))' "$OUT" \
    || { echo "error: generated manifest is not valid JSON: $OUT" >&2; exit 1; }
fi

echo "$OUT"
